






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace Site.TechNow.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// IPosts_Detail Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Posts detail</para>	
	/// <para>ID: 1469ebe1-1c10-48a1-83cb-f28a0fa25379</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPosts_DetailConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPosts_Detail : IGlassBase 
	{
			
					/// <summary>
					/// The Detail1 field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: f99b6db6-59e1-4433-8a24-e57a081598bf</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_DetailConstants.Detail1FieldName)]
					string Detail1  {get; set;}
			
			
					/// <summary>
					/// The Detail2 field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 3f865447-3fa8-4456-a047-6a26925ee240</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_DetailConstants.Detail2FieldName)]
					string Detail2  {get; set;}
			
			
					/// <summary>
					/// The Detail3 field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: b8158ae5-96ec-490e-9ca4-fe8777d77a50</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_DetailConstants.Detail3FieldName)]
					string Detail3  {get; set;}
			
			
					/// <summary>
					/// The Img1 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: a7e836af-6f6e-4d27-852e-f067e72c9f60</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_DetailConstants.Img1FieldName)]
					Image Img1  {get; set;}
			
			
					/// <summary>
					/// The Img2 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 2d734048-84fd-4704-8f25-ad92a129a779</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_DetailConstants.Img2FieldName)]
					Image Img2  {get; set;}
			
			
					/// <summary>
					/// The Img3 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 6e58ce63-0df7-4675-acfb-b120812af504</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_DetailConstants.Img3FieldName)]
					Image Img3  {get; set;}
			
			
	}


	public static partial class IPosts_DetailConstants{

			public const string TemplateIdString = "1469ebe1-1c10-48a1-83cb-f28a0fa25379";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Posts detail";

		
			
			public static readonly ID Detail1FieldId = new ID("f99b6db6-59e1-4433-8a24-e57a081598bf");
			public const string Detail1FieldName = "Detail1";
			
		
			
			public static readonly ID Detail2FieldId = new ID("3f865447-3fa8-4456-a047-6a26925ee240");
			public const string Detail2FieldName = "Detail2";
			
		
			
			public static readonly ID Detail3FieldId = new ID("b8158ae5-96ec-490e-9ca4-fe8777d77a50");
			public const string Detail3FieldName = "Detail3";
			
		
			
			public static readonly ID Img1FieldId = new ID("a7e836af-6f6e-4d27-852e-f067e72c9f60");
			public const string Img1FieldName = "Img1";
			
		
			
			public static readonly ID Img2FieldId = new ID("2d734048-84fd-4704-8f25-ad92a129a779");
			public const string Img2FieldName = "Img2";
			
		
			
			public static readonly ID Img3FieldId = new ID("6e58ce63-0df7-4675-acfb-b120812af504");
			public const string Img3FieldName = "Img3";
			
			

	}

	
	/// <summary>
	/// Posts_Detail
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Posts detail</para>	
	/// <para>ID: 1469ebe1-1c10-48a1-83cb-f28a0fa25379</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPosts_DetailConstants.TemplateIdString)] //, Cachable = true
	public partial class Posts_Detail  : GlassBase, IPosts_Detail 
	{
	   
		
				/// <summary>
				/// The Detail1 field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: f99b6db6-59e1-4433-8a24-e57a081598bf</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_DetailConstants.Detail1FieldName)]
				public virtual string Detail1  {get; set;}
					
		
				/// <summary>
				/// The Detail2 field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 3f865447-3fa8-4456-a047-6a26925ee240</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_DetailConstants.Detail2FieldName)]
				public virtual string Detail2  {get; set;}
					
		
				/// <summary>
				/// The Detail3 field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: b8158ae5-96ec-490e-9ca4-fe8777d77a50</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_DetailConstants.Detail3FieldName)]
				public virtual string Detail3  {get; set;}
					
		
				/// <summary>
				/// The Img1 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: a7e836af-6f6e-4d27-852e-f067e72c9f60</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_DetailConstants.Img1FieldName)]
				public virtual Image Img1  {get; set;}
					
		
				/// <summary>
				/// The Img2 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 2d734048-84fd-4704-8f25-ad92a129a779</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_DetailConstants.Img2FieldName)]
				public virtual Image Img2  {get; set;}
					
		
				/// <summary>
				/// The Img3 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 6e58ce63-0df7-4675-acfb-b120812af504</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_DetailConstants.Img3FieldName)]
				public virtual Image Img3  {get; set;}
					
			
	}

}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// IDasource_Template Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Dasource template</para>	
	/// <para>ID: 1600fc80-3a88-405e-97ff-fb64be04cc80</para>	
	/// </summary>
	[SitecoreType(TemplateId=IDasource_TemplateConstants.TemplateIdString )] //, Cachable = true
	public partial interface IDasource_Template : IGlassBase 
	{
			
					/// <summary>
					/// The title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b890b88c-c86c-4e25-8c83-bbbab6dfc481</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IDasource_TemplateConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class IDasource_TemplateConstants{

			public const string TemplateIdString = "1600fc80-3a88-405e-97ff-fb64be04cc80";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Dasource template";

		
			
			public static readonly ID TitleFieldId = new ID("b890b88c-c86c-4e25-8c83-bbbab6dfc481");
			public const string TitleFieldName = "title";
			
			

	}

	
	/// <summary>
	/// Dasource_Template
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Dasource template</para>	
	/// <para>ID: 1600fc80-3a88-405e-97ff-fb64be04cc80</para>	
	/// </summary>
	[SitecoreType(TemplateId=IDasource_TemplateConstants.TemplateIdString)] //, Cachable = true
	public partial class Dasource_Template  : GlassBase, IDasource_Template 
	{
	   
		
				/// <summary>
				/// The title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b890b88c-c86c-4e25-8c83-bbbab6dfc481</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IDasource_TemplateConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// ISiteweb Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Siteweb</para>	
	/// <para>ID: 1add2723-106a-498b-9f5e-9add44d2cbc4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISitewebConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISiteweb : IGlassBase 
	{
			
					/// <summary>
					/// The Title site field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: a535b8e6-b818-4081-9a6a-47be9462aa3b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISitewebConstants.Title_SiteFieldName)]
					string Title_Site  {get; set;}
			
			
	}


	public static partial class ISitewebConstants{

			public const string TemplateIdString = "1add2723-106a-498b-9f5e-9add44d2cbc4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Siteweb";

		
			
			public static readonly ID Title_SiteFieldId = new ID("a535b8e6-b818-4081-9a6a-47be9462aa3b");
			public const string Title_SiteFieldName = "Title site";
			
			

	}

	
	/// <summary>
	/// Siteweb
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Siteweb</para>	
	/// <para>ID: 1add2723-106a-498b-9f5e-9add44d2cbc4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISitewebConstants.TemplateIdString)] //, Cachable = true
	public partial class Siteweb  : GlassBase, ISiteweb 
	{
	   
		
				/// <summary>
				/// The Title site field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a535b8e6-b818-4081-9a6a-47be9462aa3b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISitewebConstants.Title_SiteFieldName)]
				public virtual string Title_Site  {get; set;}
					
			
	}

}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// IMenu_Mutilist Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Menu Mutilist</para>	
	/// <para>ID: 1d104f59-1384-442c-ab15-8fbd2a086e5f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMenu_MutilistConstants.TemplateIdString )] //, Cachable = true
	public partial interface IMenu_Mutilist : IGlassBase 
	{
			
					/// <summary>
					/// The List Menu field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 787a4414-3c23-46b2-aa80-df555c022ef8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMenu_MutilistConstants.List_MenusFieldName)]
					IEnumerable<Guid> List_Menus  {get; set;}
			
			
	}


	public static partial class IMenu_MutilistConstants{

			public const string TemplateIdString = "1d104f59-1384-442c-ab15-8fbd2a086e5f";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Menu Mutilist";

		
			
			public static readonly ID List_MenusFieldId = new ID("787a4414-3c23-46b2-aa80-df555c022ef8");
			public const string List_MenusFieldName = "List Menu";
			
			

	}

	
	/// <summary>
	/// Menu_Mutilist
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Menu Mutilist</para>	
	/// <para>ID: 1d104f59-1384-442c-ab15-8fbd2a086e5f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMenu_MutilistConstants.TemplateIdString)] //, Cachable = true
	public partial class Menu_Mutilist  : GlassBase, IMenu_Mutilist 
	{
	   
		
				/// <summary>
				/// The List Menu field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: 787a4414-3c23-46b2-aa80-df555c022ef8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMenu_MutilistConstants.List_MenusFieldName)]
				public virtual IEnumerable<Guid> List_Menus  {get; set;}
					
			
	}

}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// IImg_Template Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Img template</para>	
	/// <para>ID: 4cba5bd7-b078-451a-84b0-433404df459f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IImg_TemplateConstants.TemplateIdString )] //, Cachable = true
	public partial interface IImg_Template : IGlassBase 
	{
			
					/// <summary>
					/// The Img Post field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: f4866eb0-7882-4946-8b55-096e711d62d2</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IImg_TemplateConstants.Img_PostFieldName)]
					Image Img_Post  {get; set;}
			
			
					/// <summary>
					/// The title img field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 3e53a874-6e09-40cb-b84c-eac48d73da40</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IImg_TemplateConstants.Title_ImgFieldName)]
					string Title_Img  {get; set;}
			
			
	}


	public static partial class IImg_TemplateConstants{

			public const string TemplateIdString = "4cba5bd7-b078-451a-84b0-433404df459f";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Img template";

		
			
			public static readonly ID Img_PostFieldId = new ID("f4866eb0-7882-4946-8b55-096e711d62d2");
			public const string Img_PostFieldName = "Img Post";
			
		
			
			public static readonly ID Title_ImgFieldId = new ID("3e53a874-6e09-40cb-b84c-eac48d73da40");
			public const string Title_ImgFieldName = "title img";
			
			

	}

	
	/// <summary>
	/// Img_Template
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Img template</para>	
	/// <para>ID: 4cba5bd7-b078-451a-84b0-433404df459f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IImg_TemplateConstants.TemplateIdString)] //, Cachable = true
	public partial class Img_Template  : GlassBase, IImg_Template 
	{
	   
		
				/// <summary>
				/// The Img Post field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: f4866eb0-7882-4946-8b55-096e711d62d2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IImg_TemplateConstants.Img_PostFieldName)]
				public virtual Image Img_Post  {get; set;}
					
		
				/// <summary>
				/// The title img field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 3e53a874-6e09-40cb-b84c-eac48d73da40</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IImg_TemplateConstants.Title_ImgFieldName)]
				public virtual string Title_Img  {get; set;}
					
			
	}

}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// IHome_Template Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Home template</para>	
	/// <para>ID: 68da63ae-8b17-41ad-a20f-86655f63760d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHome_TemplateConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHome_Template : IGlassBase 
	{
			
					/// <summary>
					/// The title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 6b410a87-2098-4c6b-aeba-0e3ff86d8767</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHome_TemplateConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class IHome_TemplateConstants{

			public const string TemplateIdString = "68da63ae-8b17-41ad-a20f-86655f63760d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home template";

		
			
			public static readonly ID TitleFieldId = new ID("6b410a87-2098-4c6b-aeba-0e3ff86d8767");
			public const string TitleFieldName = "title";
			
			

	}

	
	/// <summary>
	/// Home_Template
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Home template</para>	
	/// <para>ID: 68da63ae-8b17-41ad-a20f-86655f63760d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHome_TemplateConstants.TemplateIdString)] //, Cachable = true
	public partial class Home_Template  : GlassBase, IHome_Template 
	{
	   
		
				/// <summary>
				/// The title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 6b410a87-2098-4c6b-aeba-0e3ff86d8767</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHome_TemplateConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// ICommentTemp Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/CommentTemp</para>	
	/// <para>ID: 7f2d992e-9249-4b9c-9c2f-650912953c27</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICommentTempConstants.TemplateIdString )] //, Cachable = true
	public partial interface ICommentTemp : IGlassBase 
	{
			
					/// <summary>
					/// The comment field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 3129dccf-8d97-4f7e-83f0-68985264a3f1</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentTempConstants.CommentFieldName)]
					string Comment  {get; set;}
			
			
					/// <summary>
					/// The date time field.
					/// <para></para>
					/// <para>Field Type: Datetime</para>		
					/// <para>Field ID: 5cbd79e9-34af-41d2-8539-a593a1d13040</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentTempConstants.Date_TimeFieldName)]
					DateTime Date_Time  {get; set;}
			
			
					/// <summary>
					/// The email field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: f27c246b-53af-4227-9f0b-00fbc8dba1f2</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentTempConstants.EmailFieldName)]
					string Email  {get; set;}
			
			
					/// <summary>
					/// The name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: c5c745ab-86ce-436c-a307-2dee0d01fc38</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentTempConstants.NameFieldName)]
					string Name  {get; set;}
			
			
	}


	public static partial class ICommentTempConstants{

			public const string TemplateIdString = "7f2d992e-9249-4b9c-9c2f-650912953c27";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "CommentTemp";

		
			
			public static readonly ID CommentFieldId = new ID("3129dccf-8d97-4f7e-83f0-68985264a3f1");
			public const string CommentFieldName = "comment";
			
		
			
			public static readonly ID Date_TimeFieldId = new ID("5cbd79e9-34af-41d2-8539-a593a1d13040");
			public const string Date_TimeFieldName = "date time";
			
		
			
			public static readonly ID EmailFieldId = new ID("f27c246b-53af-4227-9f0b-00fbc8dba1f2");
			public const string EmailFieldName = "email";
			
		
			
			public static readonly ID NameFieldId = new ID("c5c745ab-86ce-436c-a307-2dee0d01fc38");
			public const string NameFieldName = "name";
			
			

	}

	
	/// <summary>
	/// CommentTemp
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/CommentTemp</para>	
	/// <para>ID: 7f2d992e-9249-4b9c-9c2f-650912953c27</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICommentTempConstants.TemplateIdString)] //, Cachable = true
	public partial class CommentTemp  : GlassBase, ICommentTemp 
	{
	   
		
				/// <summary>
				/// The comment field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 3129dccf-8d97-4f7e-83f0-68985264a3f1</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentTempConstants.CommentFieldName)]
				public virtual string Comment  {get; set;}
					
		
				/// <summary>
				/// The date time field.
				/// <para></para>
				/// <para>Field Type: Datetime</para>		
				/// <para>Field ID: 5cbd79e9-34af-41d2-8539-a593a1d13040</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentTempConstants.Date_TimeFieldName)]
				public virtual DateTime Date_Time  {get; set;}
					
		
				/// <summary>
				/// The email field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f27c246b-53af-4227-9f0b-00fbc8dba1f2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentTempConstants.EmailFieldName)]
				public virtual string Email  {get; set;}
					
		
				/// <summary>
				/// The name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: c5c745ab-86ce-436c-a307-2dee0d01fc38</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentTempConstants.NameFieldName)]
				public virtual string Name  {get; set;}
					
			
	}

}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// IHeader_Template Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Header template</para>	
	/// <para>ID: 9b1862ee-48f8-4f46-b247-96edb138bab3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHeader_TemplateConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHeader_Template : IGlassBase 
	{
			
					/// <summary>
					/// The Link Contact field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 50e1f64f-7c2d-4a9a-83fb-21038baa9330</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeader_TemplateConstants.Link_ContactsFieldName)]
					IEnumerable<Guid> Link_Contacts  {get; set;}
			
			
					/// <summary>
					/// The Link Login field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 54ae26f5-1ce3-4593-a934-a63af9878ca8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeader_TemplateConstants.Link_LoginFieldName)]
					Link Link_Login  {get; set;}
			
			
					/// <summary>
					/// The Link Register field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: e0c05184-dc0b-4297-b963-5fdcb397aeaa</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeader_TemplateConstants.Link_RegisterFieldName)]
					Link Link_Register  {get; set;}
			
			
					/// <summary>
					/// The Logo Img field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 1e93eaa8-c12e-4b90-a339-a0e1339490c4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeader_TemplateConstants.Logo_ImgFieldName)]
					Image Logo_Img  {get; set;}
			
			
					/// <summary>
					/// The Time field.
					/// <para></para>
					/// <para>Field Type: Date</para>		
					/// <para>Field ID: e655cb87-3f3c-45e3-9207-393427f6ca3f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeader_TemplateConstants.TimeFieldName)]
					DateTime Time  {get; set;}
			
			
					/// <summary>
					/// The Title Login field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: a1830487-68e9-4c7b-b069-dbb06d705784</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeader_TemplateConstants.Title_LoginFieldName)]
					string Title_Login  {get; set;}
			
			
					/// <summary>
					/// The Title Register field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: a3dbfcfb-295d-4645-b40d-3bd5c97271d4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeader_TemplateConstants.Title_RegisterFieldName)]
					string Title_Register  {get; set;}
			
			
	}


	public static partial class IHeader_TemplateConstants{

			public const string TemplateIdString = "9b1862ee-48f8-4f46-b247-96edb138bab3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Header template";

		
			
			public static readonly ID Link_ContactsFieldId = new ID("50e1f64f-7c2d-4a9a-83fb-21038baa9330");
			public const string Link_ContactsFieldName = "Link Contact";
			
		
			
			public static readonly ID Link_LoginFieldId = new ID("54ae26f5-1ce3-4593-a934-a63af9878ca8");
			public const string Link_LoginFieldName = "Link Login";
			
		
			
			public static readonly ID Link_RegisterFieldId = new ID("e0c05184-dc0b-4297-b963-5fdcb397aeaa");
			public const string Link_RegisterFieldName = "Link Register";
			
		
			
			public static readonly ID Logo_ImgFieldId = new ID("1e93eaa8-c12e-4b90-a339-a0e1339490c4");
			public const string Logo_ImgFieldName = "Logo Img";
			
		
			
			public static readonly ID TimeFieldId = new ID("e655cb87-3f3c-45e3-9207-393427f6ca3f");
			public const string TimeFieldName = "Time";
			
		
			
			public static readonly ID Title_LoginFieldId = new ID("a1830487-68e9-4c7b-b069-dbb06d705784");
			public const string Title_LoginFieldName = "Title Login";
			
		
			
			public static readonly ID Title_RegisterFieldId = new ID("a3dbfcfb-295d-4645-b40d-3bd5c97271d4");
			public const string Title_RegisterFieldName = "Title Register";
			
			

	}

	
	/// <summary>
	/// Header_Template
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Header template</para>	
	/// <para>ID: 9b1862ee-48f8-4f46-b247-96edb138bab3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHeader_TemplateConstants.TemplateIdString)] //, Cachable = true
	public partial class Header_Template  : GlassBase, IHeader_Template 
	{
	   
		
				/// <summary>
				/// The Link Contact field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: 50e1f64f-7c2d-4a9a-83fb-21038baa9330</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeader_TemplateConstants.Link_ContactsFieldName)]
				public virtual IEnumerable<Guid> Link_Contacts  {get; set;}
					
		
				/// <summary>
				/// The Link Login field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 54ae26f5-1ce3-4593-a934-a63af9878ca8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeader_TemplateConstants.Link_LoginFieldName)]
				public virtual Link Link_Login  {get; set;}
					
		
				/// <summary>
				/// The Link Register field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: e0c05184-dc0b-4297-b963-5fdcb397aeaa</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeader_TemplateConstants.Link_RegisterFieldName)]
				public virtual Link Link_Register  {get; set;}
					
		
				/// <summary>
				/// The Logo Img field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 1e93eaa8-c12e-4b90-a339-a0e1339490c4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeader_TemplateConstants.Logo_ImgFieldName)]
				public virtual Image Logo_Img  {get; set;}
					
		
				/// <summary>
				/// The Time field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: e655cb87-3f3c-45e3-9207-393427f6ca3f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeader_TemplateConstants.TimeFieldName)]
				public virtual DateTime Time  {get; set;}
					
		
				/// <summary>
				/// The Title Login field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a1830487-68e9-4c7b-b069-dbb06d705784</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeader_TemplateConstants.Title_LoginFieldName)]
				public virtual string Title_Login  {get; set;}
					
		
				/// <summary>
				/// The Title Register field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a3dbfcfb-295d-4645-b40d-3bd5c97271d4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeader_TemplateConstants.Title_RegisterFieldName)]
				public virtual string Title_Register  {get; set;}
					
			
	}

}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// IPopular_News Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Popular News</para>	
	/// <para>ID: 9b42572a-48a1-48f6-babf-b770936f5ccb</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPopular_NewsConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPopular_News : IGlassBase 
	{
			
					/// <summary>
					/// The List posts field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 46d2e179-6639-48de-8a7b-c2d5779837dc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPopular_NewsConstants.List_PostsFieldName)]
					IEnumerable<Guid> List_Posts  {get; set;}
			
			
					/// <summary>
					/// The title popular field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 2c215c9d-9c7f-48e0-a22d-9728d92cfb10</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPopular_NewsConstants.Title_PopularFieldName)]
					string Title_Popular  {get; set;}
			
			
	}


	public static partial class IPopular_NewsConstants{

			public const string TemplateIdString = "9b42572a-48a1-48f6-babf-b770936f5ccb";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Popular News";

		
			
			public static readonly ID List_PostsFieldId = new ID("46d2e179-6639-48de-8a7b-c2d5779837dc");
			public const string List_PostsFieldName = "List posts";
			
		
			
			public static readonly ID Title_PopularFieldId = new ID("2c215c9d-9c7f-48e0-a22d-9728d92cfb10");
			public const string Title_PopularFieldName = "title popular";
			
			

	}

	
	/// <summary>
	/// Popular_News
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Popular News</para>	
	/// <para>ID: 9b42572a-48a1-48f6-babf-b770936f5ccb</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPopular_NewsConstants.TemplateIdString)] //, Cachable = true
	public partial class Popular_News  : GlassBase, IPopular_News 
	{
	   
		
				/// <summary>
				/// The List posts field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: 46d2e179-6639-48de-8a7b-c2d5779837dc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPopular_NewsConstants.List_PostsFieldName)]
				public virtual IEnumerable<Guid> List_Posts  {get; set;}
					
		
				/// <summary>
				/// The title popular field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2c215c9d-9c7f-48e0-a22d-9728d92cfb10</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPopular_NewsConstants.Title_PopularFieldName)]
				public virtual string Title_Popular  {get; set;}
					
			
	}

}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// IPage_Site Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Page site</para>	
	/// <para>ID: a2ea636d-fbfa-4f7d-89cd-e8c4f2522429</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_SiteConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPage_Site : IGlassBase 
	{
			
					/// <summary>
					/// The TitePage field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 27ccff4d-3e7a-4326-97d7-69f8f7aad08a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPage_SiteConstants.TitePageFieldName)]
					string TitePage  {get; set;}
			
			
					/// <summary>
					/// The UrlPage field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 1def3aaa-6131-49d5-a348-d59a01e824c2</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPage_SiteConstants.UrlPageFieldName)]
					Link UrlPage  {get; set;}
			
			
	}


	public static partial class IPage_SiteConstants{

			public const string TemplateIdString = "a2ea636d-fbfa-4f7d-89cd-e8c4f2522429";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Page site";

		
			
			public static readonly ID TitePageFieldId = new ID("27ccff4d-3e7a-4326-97d7-69f8f7aad08a");
			public const string TitePageFieldName = "TitePage";
			
		
			
			public static readonly ID UrlPageFieldId = new ID("1def3aaa-6131-49d5-a348-d59a01e824c2");
			public const string UrlPageFieldName = "UrlPage";
			
			

	}

	
	/// <summary>
	/// Page_Site
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Page site</para>	
	/// <para>ID: a2ea636d-fbfa-4f7d-89cd-e8c4f2522429</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_SiteConstants.TemplateIdString)] //, Cachable = true
	public partial class Page_Site  : GlassBase, IPage_Site 
	{
	   
		
				/// <summary>
				/// The TitePage field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 27ccff4d-3e7a-4326-97d7-69f8f7aad08a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPage_SiteConstants.TitePageFieldName)]
				public virtual string TitePage  {get; set;}
					
		
				/// <summary>
				/// The UrlPage field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 1def3aaa-6131-49d5-a348-d59a01e824c2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPage_SiteConstants.UrlPageFieldName)]
				public virtual Link UrlPage  {get; set;}
					
			
	}

}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// IPosts_Template Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Posts template</para>	
	/// <para>ID: c38072b3-50fa-4608-977d-f2cd6f18b211</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPosts_TemplateConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPosts_Template : IGlassBase , global::Site.TechNow.Models.sitecore.templates.TechNow_template.IPosts_Detail, global::Site.TechNow.Models.sitecore.templates.TechNow_template.IImg_Template
	{
			
					/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 7a1e17e2-f032-4130-953b-51b122634fde</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TemplateConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
			
					/// <summary>
					/// The Time Post field.
					/// <para></para>
					/// <para>Field Type: Datetime</para>		
					/// <para>Field ID: 34baa4ad-1c75-4390-8f8d-34b7f20a52ad</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TemplateConstants.Time_PostFieldName)]
					DateTime Time_Post  {get; set;}
			
			
					/// <summary>
					/// The Title Post field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ae6a069f-9d23-4b60-bfb4-405c016fc6ba</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TemplateConstants.Title_PostFieldName)]
					string Title_Post  {get; set;}
			
			
	}


	public static partial class IPosts_TemplateConstants{

			public const string TemplateIdString = "c38072b3-50fa-4608-977d-f2cd6f18b211";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Posts template";

		
			
			public static readonly ID DescriptionFieldId = new ID("7a1e17e2-f032-4130-953b-51b122634fde");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID Time_PostFieldId = new ID("34baa4ad-1c75-4390-8f8d-34b7f20a52ad");
			public const string Time_PostFieldName = "Time Post";
			
		
			
			public static readonly ID Title_PostFieldId = new ID("ae6a069f-9d23-4b60-bfb4-405c016fc6ba");
			public const string Title_PostFieldName = "Title Post";
			
		
			
			public static readonly ID Detail1FieldId = new ID("f99b6db6-59e1-4433-8a24-e57a081598bf");
			public const string Detail1FieldName = "Detail1";
			
		
			
			public static readonly ID Detail2FieldId = new ID("3f865447-3fa8-4456-a047-6a26925ee240");
			public const string Detail2FieldName = "Detail2";
			
		
			
			public static readonly ID Detail3FieldId = new ID("b8158ae5-96ec-490e-9ca4-fe8777d77a50");
			public const string Detail3FieldName = "Detail3";
			
		
			
			public static readonly ID Img1FieldId = new ID("a7e836af-6f6e-4d27-852e-f067e72c9f60");
			public const string Img1FieldName = "Img1";
			
		
			
			public static readonly ID Img2FieldId = new ID("2d734048-84fd-4704-8f25-ad92a129a779");
			public const string Img2FieldName = "Img2";
			
		
			
			public static readonly ID Img3FieldId = new ID("6e58ce63-0df7-4675-acfb-b120812af504");
			public const string Img3FieldName = "Img3";
			
		
			
			public static readonly ID Img_PostFieldId = new ID("f4866eb0-7882-4946-8b55-096e711d62d2");
			public const string Img_PostFieldName = "Img Post";
			
		
			
			public static readonly ID Title_ImgFieldId = new ID("3e53a874-6e09-40cb-b84c-eac48d73da40");
			public const string Title_ImgFieldName = "title img";
			
			

	}

	
	/// <summary>
	/// Posts_Template
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Posts template</para>	
	/// <para>ID: c38072b3-50fa-4608-977d-f2cd6f18b211</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPosts_TemplateConstants.TemplateIdString)] //, Cachable = true
	public partial class Posts_Template  : GlassBase, IPosts_Template 
	{
	   
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 7a1e17e2-f032-4130-953b-51b122634fde</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TemplateConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Time Post field.
				/// <para></para>
				/// <para>Field Type: Datetime</para>		
				/// <para>Field ID: 34baa4ad-1c75-4390-8f8d-34b7f20a52ad</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TemplateConstants.Time_PostFieldName)]
				public virtual DateTime Time_Post  {get; set;}
					
		
				/// <summary>
				/// The Title Post field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ae6a069f-9d23-4b60-bfb4-405c016fc6ba</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TemplateConstants.Title_PostFieldName)]
				public virtual string Title_Post  {get; set;}
					
		
				/// <summary>
				/// The Detail1 field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: f99b6db6-59e1-4433-8a24-e57a081598bf</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TemplateConstants.Detail1FieldName)]
				public virtual string Detail1  {get; set;}
					
		
				/// <summary>
				/// The Detail2 field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 3f865447-3fa8-4456-a047-6a26925ee240</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TemplateConstants.Detail2FieldName)]
				public virtual string Detail2  {get; set;}
					
		
				/// <summary>
				/// The Detail3 field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: b8158ae5-96ec-490e-9ca4-fe8777d77a50</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TemplateConstants.Detail3FieldName)]
				public virtual string Detail3  {get; set;}
					
		
				/// <summary>
				/// The Img1 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: a7e836af-6f6e-4d27-852e-f067e72c9f60</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TemplateConstants.Img1FieldName)]
				public virtual Image Img1  {get; set;}
					
		
				/// <summary>
				/// The Img2 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 2d734048-84fd-4704-8f25-ad92a129a779</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TemplateConstants.Img2FieldName)]
				public virtual Image Img2  {get; set;}
					
		
				/// <summary>
				/// The Img3 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 6e58ce63-0df7-4675-acfb-b120812af504</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TemplateConstants.Img3FieldName)]
				public virtual Image Img3  {get; set;}
					
		
				/// <summary>
				/// The Img Post field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: f4866eb0-7882-4946-8b55-096e711d62d2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TemplateConstants.Img_PostFieldName)]
				public virtual Image Img_Post  {get; set;}
					
		
				/// <summary>
				/// The title img field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 3e53a874-6e09-40cb-b84c-eac48d73da40</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TemplateConstants.Title_ImgFieldName)]
				public virtual string Title_Img  {get; set;}
					
			
	}

}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// ILink_Action Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Link Action</para>	
	/// <para>ID: da1c04ac-e05b-4b6d-abc6-00f019c96ec0</para>	
	/// </summary>
	[SitecoreType(TemplateId=ILink_ActionConstants.TemplateIdString )] //, Cachable = true
	public partial interface ILink_Action : IGlassBase 
	{
			
					/// <summary>
					/// The Img link field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: c3dd91f9-632f-4bd0-bf73-c1837ea93c64</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ILink_ActionConstants.Img_LinkFieldName)]
					string Img_Link  {get; set;}
			
			
					/// <summary>
					/// The Link field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 261a047b-06a2-4081-a386-f08263dfeecc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ILink_ActionConstants.LinkFieldName)]
					Link Link  {get; set;}
			
			
					/// <summary>
					/// The Title Link field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 541004fd-06ed-456e-9a45-1ae36a1885a6</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ILink_ActionConstants.Title_LinkFieldName)]
					string Title_Link  {get; set;}
			
			
	}


	public static partial class ILink_ActionConstants{

			public const string TemplateIdString = "da1c04ac-e05b-4b6d-abc6-00f019c96ec0";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Link Action";

		
			
			public static readonly ID Img_LinkFieldId = new ID("c3dd91f9-632f-4bd0-bf73-c1837ea93c64");
			public const string Img_LinkFieldName = "Img link";
			
		
			
			public static readonly ID LinkFieldId = new ID("261a047b-06a2-4081-a386-f08263dfeecc");
			public const string LinkFieldName = "Link";
			
		
			
			public static readonly ID Title_LinkFieldId = new ID("541004fd-06ed-456e-9a45-1ae36a1885a6");
			public const string Title_LinkFieldName = "Title Link";
			
			

	}

	
	/// <summary>
	/// Link_Action
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Link Action</para>	
	/// <para>ID: da1c04ac-e05b-4b6d-abc6-00f019c96ec0</para>	
	/// </summary>
	[SitecoreType(TemplateId=ILink_ActionConstants.TemplateIdString)] //, Cachable = true
	public partial class Link_Action  : GlassBase, ILink_Action 
	{
	   
		
				/// <summary>
				/// The Img link field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: c3dd91f9-632f-4bd0-bf73-c1837ea93c64</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILink_ActionConstants.Img_LinkFieldName)]
				public virtual string Img_Link  {get; set;}
					
		
				/// <summary>
				/// The Link field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 261a047b-06a2-4081-a386-f08263dfeecc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILink_ActionConstants.LinkFieldName)]
				public virtual Link Link  {get; set;}
					
		
				/// <summary>
				/// The Title Link field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 541004fd-06ed-456e-9a45-1ae36a1885a6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILink_ActionConstants.Title_LinkFieldName)]
				public virtual string Title_Link  {get; set;}
					
			
	}

}
namespace Site.TechNow.Models.sitecore.templates.TechNow_template
{


 	/// <summary>
	/// IFeature_New Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Feature new</para>	
	/// <para>ID: da6c812b-b670-4037-b332-f5761fdebc00</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFeature_NewConstants.TemplateIdString )] //, Cachable = true
	public partial interface IFeature_New : IGlassBase 
	{
			
					/// <summary>
					/// The list new field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: e3b7f376-4746-4590-a91b-306298d92836</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IFeature_NewConstants.List_NewsFieldName)]
					IEnumerable<Guid> List_News  {get; set;}
			
			
	}


	public static partial class IFeature_NewConstants{

			public const string TemplateIdString = "da6c812b-b670-4037-b332-f5761fdebc00";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Feature new";

		
			
			public static readonly ID List_NewsFieldId = new ID("e3b7f376-4746-4590-a91b-306298d92836");
			public const string List_NewsFieldName = "list new";
			
			

	}

	
	/// <summary>
	/// Feature_New
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechNow template/Feature new</para>	
	/// <para>ID: da6c812b-b670-4037-b332-f5761fdebc00</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFeature_NewConstants.TemplateIdString)] //, Cachable = true
	public partial class Feature_New  : GlassBase, IFeature_New 
	{
	   
		
				/// <summary>
				/// The list new field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: e3b7f376-4746-4590-a91b-306298d92836</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IFeature_NewConstants.List_NewsFieldName)]
				public virtual IEnumerable<Guid> List_News  {get; set;}
					
			
	}

}
